import React from "react";
import ListaVerduras from "../componentes/listaVerduras";

export default class PaginaVerduras extends React.Component {
  Verduras = [
     {nombre: 'Espinaca', img: '/img/Espinaca.webp', descripcion: 'Originaria de Persia (Irán) y se cree que se cultivaba hace más de 2000 años. Se extendió a través de Asia y Europa y eventualmente llegó a América del Norte en el siglo XIX. Hoy en día, la espinaca se cultiva en muchas partes del mundo y es conocida por ser una verdura nutritiva y versátil.', beneficios: 'Es una verdura altamente nutritiva, rica en vitaminas y minerales que benefician la salud ósea, cardiovascular y ocular. Además, su contenido de antioxidantes y fibra la hace excelente para la digestión y el control del peso. Incorporar espinaca en la dieta puede ser una forma simple de mejorar la salud en general.'},    
     {nombre: 'Zanahoria', img: '/img/zanahoria.jpg', descripcion: 'Es originaria de Persia y se cultiva desde hace más de 2,000 años. Inicialmente las zanahorias eran de color púrpura o amarillo, y no fue hasta el siglo XVII en los Países Bajos que se desarrollaron las variedades de zanahorias naranjas que conocemos hoy en día. Se ha extendido por todo el mundo y es una de las hortalizas más populares y consumidas.', beneficios: 'Son excelentes para la salud ocular debido a su alto contenido de vitamina A y betacaroteno. También benefician la piel, fortalecen el sistema inmunológico, promueven una digestión saludable y pueden ayudar en la prevención de enfermedades cardíacas. Su contenido de fibra las hace ideales para controlar el peso y mantener una buena salud digestiva. Además, su consumo puede estimular la producción de saliva, lo que contribuye a la salud bucal. Incorporar zanahorias en tu dieta diaria puede tener numerosos beneficios para la salud.'},    
     {nombre: 'Brocoli', img: '/img/brocoli.jpg', descripcion: 'Es originario de la región mediterránea y Asia Menor, cultivado desde la antigüedad. Llevado a Italia por los romanos, se extendió por Europa y América del Norte. Desarrollado en el siglo XVI en Italia, el brócoli moderno se cultiva en todo el mundo y es apreciado por su sabor y beneficios para la salud.', beneficios: 'Es una verdura muy saludable, rica en nutrientes esenciales. Contiene una alta cantidad de vitamina C, que ayuda a fortalecer el sistema inmunológico y a prevenir enfermedades. También es una buena fuente de fibra, que es importante para la salud digestiva y puede ayudar a reducir el colesterol. Además, el brócoli contiene antioxidantes que pueden ayudar a reducir el riesgo de enfermedades cardíacas y ciertos tipos de cáncer. Incorporar brócoli en tu dieta regular puede ser una forma fácil y deliciosa de mejorar tu salud.'},
     {nombre: 'Tomate', img: '/img/tomate.jpg', descripcion: 'Es originario de América del Sur, específicamente de la región que ahora comprende partes de Perú, Ecuador, Colombia y Bolivia. Se cree que los antiguos pueblos indígenas de estas regiones cultivaban y consumían tomates mucho antes de que llegaran a Europa y otras partes del mundo. Los tomates fueron llevados a Europa en el siglo XVI por los exploradores españoles y portugueses, y desde entonces se han convertido en un alimento básico en muchas cocinas de todo el mundo.', beneficios: 'Son una excelente fuente de antioxidantes, como la vitamina C y el licopeno, que ayudan a combatir enfermedades y protegen la piel y los ojos. También son bajos en calorías, ricos en fibra y beneficiosos para la salud cardiovascular y ósea. Incorporar tomates en tu dieta puede ser una forma deliciosa de mejorar tu salud en general.'},
     {nombre: 'Remolacha', img: '/img/remolacha.webp', descripcion: 'Originaria del Mediterráneo, era cultivada por griegos y romanos. La variedad silvestre se encontraba en las costas mediterráneas y Asia. Ha sido cultivada globalmente por sus raíces comestibles y hojas.', beneficios: 'Es rica en antioxidantes, beneficia la salud cardiovascular y digestiva, y ayuda en el control del peso. También mejora el rendimiento deportivo, tiene propiedades antiinflamatorias, y puede mejorar la función cognitiva y la salud de la piel debido a su contenido de nitratos y vitamina C. Además, actúa como desintoxicante, ayudando a eliminar toxinas y fortaleciendo el sistema inmunológico.'},
  ]

  render() {
    return (
      <>
         <h6 className="my-5 p-3 pp align-items-center "><h1>Verduras</h1> Las verduras son partes comestibles de plantas que aportan vitaminas, minerales, fibra y antioxidantes. Son bajas en calorías y ayudan a mantener la salud digestiva, reducir el riesgo de enfermedades crónicas y mantener un peso saludable. Incorporar una variedad de verduras en la dieta es beneficioso para la salud general.</h6>
        <ListaVerduras Nutri={this.Verduras} />
      </>
    );
  }
}